### ISSUE TITLE
It's works but with few limitations

### ISSUE THREAD

**Issue by viriatusX** [ItzNotABug/ghosler#2]
Hi!
first of all thank you for the work done. It works correctly!
I have a question... The newsletter that arrives does not have the design and options that Ghost "officially" includes with MailGun. Can't this be solved?

Thanks

**Comment by ItzNotABug** [comment]
Hi there,
Thanks for trying out the project!

I tried to mimic the design by looking at the "Preview" shown on Ghost as I didn't have the source of the complete html.
I agree that it isn't exactly the same but I can definitely try to improve it.

You also mentioned some "options", could you tell what those are?

**Comment by viriatusX** [comment]
> Hi there, Thanks for trying out the project!
> 
> I tried to mimic the design by looking at the "Preview" shown on Ghost as I didn't have the source of the complete html. I agree that it isn't exactly the same but I can definitely try to improve it.
> 
> You also mentioned some "options", could you tell what those are?

Thank you for your response. The project is great. It really is.
The design issue only. The Ghost template is beautiful. Too bad they don't share the HTML to mimic it in your service. I'll keep an eye out for updates.

**Comment by ItzNotABug** [comment]
Just an update, I'm mostly done with the native-ish look of the template. Improvements also include:
1. Align Title (Center or Left)
2. Manage Subscriptions Section

Both options configurable via Ghosler settings.

Will create a branch, probably tomorrow for public access & testing.

**Comment by viriatusX** [comment]
> Just an update, I'm mostly done with the native-ish look of the template. Improvements also include:
> 
> 1. Align Title (Center or Left)
> 2. Manage Subscriptions Section
> 
> Both options configurable via Ghosler settings.
> 
> Will create a branch, probably tomorrow for public access & testing.

It's awesome! I'll keep an eye out 👏☺️

**Comment by ItzNotABug** [comment]
See the branch : https://github.com/ItzNotABug/ghosler/tree/improved-template.
Let me know if you have suggestions or find any issues with the new template.

Cheers!

**Comment by viriatusX** [comment]
> See the branch : https://github.com/ItzNotABug/ghosler/tree/improved-template. Let me know if you have suggestions or find any issues with the new template.
> 
> Cheers!

Great job. Now, the template is sent with Ghost's design! 🥇 

I send you a couple of bugs. 
1. The logo comes out "square", not in its original look.
2. The site title has no CSS styling.

Now possible suggestions (if possible)
1. Is it possible to change the typography of the article title?
2. Is it possible to add the Excerpt (subheading) of the article below the title?
3. Is it possible to add the "Keep reading" and "More like this / Less like this"?

Thank you very much for everything.


![CleanShot 2023-12-13 at 17 01 10@2x](https://github.com/ItzNotABug/ghosler/assets/64467637/97e46ac9-a519-4af5-b47e-550619635b04)


![CleanShot 2023-12-13 at 16 59 07@2x](https://github.com/ItzNotABug/ghosler/assets/64467637/9ba9da16-d82a-4661-be4b-3d8026b4d4b9)

**Comment by ItzNotABug** [comment]
Hi again 👋

### Bugs.
1. I don't think I've really changed much of the logo's style. Afaik the logo always shows up in square style by default.
See [Logo Section](https://github.com/ItzNotABug/ghosler/blob/4675051260581e57607ec966ff048838afb48050/views/newsletter.ejs#L269C49-L281C54).

2. The site title indeed does not have any styling by default, You can either select `Classic Serif` or `Serif` on Ghost Newsletter design page. I used `Serif` as default. See [Site Title Section](https://github.com/ItzNotABug/ghosler/blob/4675051260581e57607ec966ff048838afb48050/views/newsletter.ejs#L288C57-L290C98).

 If you need more designing, feel free to make relevant changes to `newsletter.ejs` & restart Ghosler with `pm2 restart ghosler`.

### Suggestions.
> 1. Is it possible to change the typography of the article title?

I have tried to keep it as close as the actual template but you can always tweak as per your changes as described above.

> 2. Is it possible to add the Excerpt (subheading) of the article below the title?

Again, you can. The excerpt is stored in the `post.preview` variable.
This is actually used for email client's preview text. See how it is generated [here](https://github.com/ItzNotABug/ghosler/blob/4675051260581e57607ec966ff048838afb48050/utils/models/post.js#L65).

> 3. Is it possible to add the "Keep reading" and "More like this / Less like this"?

I did experiment with `More like this` & `Less like this` options. But adding them wouldn't work as expected though.
See you can send a user to get a feedback on a post BUT the feedback will not be displayed on the Analytics dashboard as it is not sent via Ghost x Mailgun. I am not really sure of tracking this user feedback on Ghosler at the moment though.

About the `Keep Reading` part, I'll have to see about this.

Thanks!

**Comment by viriatusX** [comment]
Thanks for all!
Last question: How can I remove the word "Newsletter" from the title of the email so that only the title of the article appears?

**Comment by ItzNotABug** [comment]
Nice catch, I'll probably add something for that as well.

Till then, [this](https://github.com/ItzNotABug/ghosler/blob/4675051260581e57607ec966ff048838afb48050/utils/mail/mailer.js#L26) is the line.

As before, make changes & do `pm2 restart ghosler`.

**Comment by viriatusX** [comment]
I keep discovering bugs to polish Ghosler :P

If the article is set to "members only", in the email that arrives you can read the entire article. With the official implementation, this does not happen.

And, the HTML code inserted in the article (e.g. bookmarks, divider, button, etc.) is also not displayed correctly.

**Comment by ItzNotABug** [comment]
Can you provide some more info about the Members only article issue?

For the second one, there are a lot of components that Ghost supports, some of them are custom and require additional css styles. I don't intent to add all the css as that would bloat the html file.
Pretty sure that [this](https://github.com/TryGhost/Ghost/blob/7b0ec35a1f4be3a4456a7d6c6be28cd796f47361/ghost/email-service/lib/email-templates/partials/styles.hbs) is the file, huge if you see.

I'll keep checking for usual html tags and add respective CSS in the template over the course of time.

Also if the issue differs from design, make sure to create a new issue.

Thanks for all the feedback.

**Comment by ItzNotABug** [comment]
> If the article is set to "members only", in the email that arrives you can read the entire article. With the official implementation, this does not happen.

When the post is set to 'Paid Members Only' or 'Tiers', only the said members should receive the full content.
Others, i.e. non-paying members receive only the 'Public Content' with an option to 'Subscribe' to the blog.
This is now fully supported in the latest `improved-template` branch!

Closing this issue.
Create a new one for suggestions.
Thanks again for all the feedback!

**Comment by viriatusX** [comment]
Hi @ItzNotABug 
Now the tool works perfectly!

Only one thing:
When you receive the email, in the "Site title" is added a final " ' ". I can't find where to delete it.

![CleanShot 2023-12-15 at 23 10 28@2x](https://github.com/ItzNotABug/ghosler/assets/64467637/e104c563-a2b7-44a7-989b-24becd94ad27)

Thanks!!

**Comment by ItzNotABug** [comment]
@viriatusX I don't see this issue. Can you check if your 'From' field in the added mail config has an extra `'`?

**Comment by viriatusX** [comment]
> @viriatusX I don't see this issue. Can you check if your 'From' field in the added mail config has an extra `'`?

I look like an idiot. That was it. Thanks for your effort!

**Comment by ItzNotABug** [comment]
No issues.
Don't forget to ⭐️ the project!
