### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by viriatusX** [ItzNotABug/ghosler#23]
I just upgraded to the latest version and it won't let me log in. It shows this error all the time. I have tried rebooting, it doesn't work.

<img width="871" alt="Captura de pantalla 2024-01-07 a las 17 57 02" src="https://github.com/ItzNotABug/ghosler/assets/64467637/ea148b1e-2901-46a3-8ebc-f412a52d8a5d">

**Comment by ItzNotABug** [comment]
Are you on the latest version?
Also from which version did you update?

**Comment by viriatusX** [comment]
Yes
I have version 0.8.6. I have updated from 0.8.4 with "ghost update". No errors

**Comment by ItzNotABug** [comment]
Update from `0.84` to `0.86` shouldn't be a problem at all, I'll check once. Also, are you sure you did `ghosler update`?

**Comment by ItzNotABug** [comment]
I see the error now, it happens if you enter the wrong credentials. Works fine if the password if correct.

**Comment by viriatusX** [comment]
> I see the error now, it happens if you enter the wrong password. Works fine if the password if correct.

I just removed Ghosler and reinstalled it and everything is OK. Glad to know it's not a bug in the app :)

**Comment by ItzNotABug** [comment]
Its actually a minor bug. Will fix it.
