### ISSUE TITLE
Email Per Second Limits with SES

### ISSUE THREAD

**Issue by ItzNotABug** [ItzNotABug/ghosler#25]
Hi @ItzNotABug 

I am not opening an incident as it is more of a query than an incident. I have contracted AWS SES as my SMTP provider. I have a limit of 50K/day and 14 emails per second. Something curious happens. Ghosler has managed to send 588 of the 1352 emails correctly.

I ask with ignorance. I have seen that Ghosler uses nodemailer. Is this configured in your program as infinite? https://medium.com/@susanne.lundkvist/using-nodemailer-to-send-bulk-emails-cbad289fce0e

I don't know if Nodemailer will be blocking so much mass mailing as well.

Ghosler shows this error: 

[2024-01-08 17:59:39 UTC] => [ERROR] => Newsletter: Error: Message failed: 454 Throttling failure: Maximum sending rate exceeded.

It shows as if it is checking the AWS SES limit, but this is not the case. Googling I see this article from 2015 (https://github.com/nodemailer/nodemailer/issues/436) also about the same "pool" issue.

If nodemailer is not the problem. Is there a way for Ghosler to detect the members that did not receive the email and do a "retry".  If it detects that there are 1352 members (in my case) but only 588 emails sent. I don't know if it detects which emails could not be sent, and proceed with a retry. 
Or adding some "queue" for emails.

Thanks!!

<img width="745" alt="Captura de pantalla 2024-01-08 a las 20 18 32" src="https://github.com/ItzNotABug/ghosler/assets/64467637/bd9d0bd7-936d-4fc9-b6fd-e1eefd3a60e5">

_Originally posted by @viriatusX in https://github.com/ItzNotABug/ghosler/issues/14#issuecomment-1881686017_

**Comment by viriatusX** [comment]
Thanks for your work. Tomorrow I will publish a new article and I will be able to test it.
I asked SES for an increase and they have charged me 200K/day and 100 per second.
With these parameters in Ghosler, I should have no problem tomorrow, right?

<img width="667" alt="Captura de pantalla 2024-01-09 a las 16 36 08" src="https://github.com/ItzNotABug/ghosler/assets/64467637/b03bda05-f603-49b9-a24b-5ba60e496731">
<img width="1205" alt="Captura de pantalla 2024-01-09 a las 16 36 59" src="https://github.com/ItzNotABug/ghosler/assets/64467637/ee06bff0-466a-4030-9a14-32379b1ccc41">


I will give you an answer tomorrow. 
Thanks again

**Comment by ItzNotABug** [comment]
That should probably work. Let me know how it goes!

Maybe I'll subscribe to the newsletter too, haha!

**Comment by viriatusX** [comment]
Now yes!!!!! Works perfectly!!
Have you received the newsletter? :)

![Captura de pantalla 2024-01-09 a las 20 04 44](https://github.com/ItzNotABug/ghosler/assets/64467637/8aca60a4-e80c-4754-866d-ca7d7754794a)

**Comment by ItzNotABug** [comment]
@viriatusX That's great to hear!
And Yes, I did receive the newsletter email! 🚀

Would you have some idea as to how much time did it take overall?

**Comment by viriatusX** [comment]
Ghosler did it in 36 batches. I didn't count the exact seconds. But less than 2 minutes for sure. From what I saw, it went from 0 sent in "sending" status to 1353 in "sent" status. All correct without any error logs. The time it took is perfect

Thanks for your work seriously 👏

**Comment by ItzNotABug** [comment]
This is fixed via the previously linked PR #26.
Thanks for the report & the testing @viriatusX.

Feel free to open a new issue if you find any other problem.
