### ISSUE TITLE
Multiple Newsletter 

### ISSUE THREAD

**Issue by viriatusX** [ItzNotABug/ghosler#30]
Hi!
Is it possible to finally have multiple newsletters? Or is it going to be difficult?
Thanks for your work.

**Comment by ItzNotABug** [comment]
Hi @viriatusX,
I haven't decided a flow for this yet. Its not really very hard but requires a bit of time and will also create breaking changes.

This is indeed on my roadmap for Ghosler, just not at the moment.

I'll keep this issue open though.

**Comment by ItzNotABug** [comment]
Update: I've internally started working on this. No ETAs though.

**Comment by viriatusX** [comment]
GREAT! 😍🙌

**Comment by ItzNotABug** [comment]
Update: The linked branch i.e. [multiple-newsletters](https://github.com/ItzNotABug/ghosler/tree/multiple-newsletters) contains this feature request.

**Comment by viriatusX** [comment]
> Update: The linked branch i.e. [multiple-newsletters](https://github.com/ItzNotABug/ghosler/tree/multiple-newsletters) contains this feature request.

Great!!! is there any way to install this branch in second instance without damaging the main app installed by ghosler cli? I have the service running and I don't want to mess it up. 

Thanks!

**Comment by ItzNotABug** [comment]
@viriatusX You can install `ghosler` from the mentioned branch in a different directory.

However it will require a manual setup as `ghosler-cli` doesn't currently support managing multiple instances.

Here's a basic flow to test the branch -
1. Git clone the branch to a directory.
2. Run `npm ci --omit-dev && pm2 start app.js --name ghosler-dev` in the directory.

I'll be verifying this branch too before merging the linked PR but no timeline on it as I'm travelling for a while.

Thanks!

**Comment by viriatusX** [comment]
@ItzNotABug It's work perfectly! I just test it!

Two things:

1. It would be nice to have an option to send the article to ALL newsletters.
2. One more suggestion: Add a checkbox in "newsletter settings" that enables multiple newsletters. If it is NOT checked, the article will be sent automatically as it is now. If it is checked, you have to launch it from Ghosler with the new method.


Thanks for all!

**Comment by ItzNotABug** [comment]
@viriatusX Thanks for testing!
About the suggestion, I don't think we should allow sending to 'all' newsletter or 'multiple newsletters'.

The reason being, a user may be subscribed to multiple newsletters & hence would receive multiple emails for the same blog post.

However, we could add an option to send the email to 'all' subscribed users, irrespective of a newsletter which makes sure that every user receives only one email.

**Comment by ItzNotABug** [comment]
@viriatusX Here's what I meant - https://github.com/ItzNotABug/ghosler/pull/32#issuecomment-1936959053.

**Comment by viriatusX** [comment]
Perfect 🙌👏
