### ISSUE TITLE
Container Build

### ISSUE THREAD

**Issue by psharma04** [ItzNotABug/ghosler#31]
It would be nice to have a containerised version of this (via Dockerfile or other means).

**Comment by ItzNotABug** [comment]
Hey @psharma04,
That would be a good idea but I do not have enough experience with Docker. If you do, a PR would be great!

In the meantime, you could use the `ghosler-cli` which is pretty straightforward to manage the app.

Thanks.

**Comment by viriatusX** [comment]
I currently have an Ubuntu VM running 24/7 for Ghosler. A Docker version would be awesome. See if any users can help 🙏.

**Comment by viriatusX** [comment]
Hi! @ItzNotABug 

<img width="1312" alt="Captura de pantalla 2024-03-03 a las 14 33 49" src="https://github.com/ItzNotABug/ghosler/assets/64467637/65acb42e-e8a0-48e8-94ba-09e9c0fd8254">

I have managed to get Ghosler in Docker, but there is a bug.
When I run "ghosler restart" it shows this error and does not work.

Any ideas?

**Comment by ItzNotABug** [comment]
What process names are returned if you do `pm2 ls`?

**Comment by viriatusX** [comment]
> What process names are returned if you do `pm2 ls`?

Nothing..

<img width="1312" alt="Captura de pantalla 2024-03-03 a las 14 38 17" src="https://github.com/ItzNotABug/ghosler/assets/64467637/481a505b-5a05-49b4-b492-28ffad6eaa21">

**Comment by ItzNotABug** [comment]
I am not sure if `ghosler` is installed in the docker container.
If it is, I am not sure how you got it started? (`node app.js?`)
The container must have access to the `pm2` which manages the whole `ghosler` instance for restarts, updates, etc.

**Comment by viriatusX** [comment]
> I am not sure if `ghosler` is installed in the docker container. If it is, I am not sure how you got it started? (`node app.js?`) The container must have access to the `pm2` which manages the whole `ghosler` instance for restarts, updates, etc.

Ok, for now:

- If I start with "Node app.js", Ghosler's Docker starts without problems, but if I do "pm2 List" it comes up empty.

- If I start with "pm2 start app.js --name ghosler", the Ghosler Docker creates the pm2 process but the docker container stops automatically, it doesn't work.

**Comment by ItzNotABug** [comment]
Using `node app.js` is probably fine inside a docker container and you may not even need PM2 for this. Of-course I could be wrong due to my limited experience with Docker.

**Comment by viriatusX** [comment]
Ready. I got it through "pm2-runtime".
I will publish a tutorial this week in my Blog.
**Ghosler can officially run on Docker :)**

**Comment by ItzNotABug** [comment]
That's great 🚀!
Waiting for the article!

**Comment by viriatusX** [comment]
The tutorial is ready! 🚀 

[Ghosler Docker](https://hdsplus.co/ghosler-envio-de-emails-y-newsletter-con-ghost-desde-cualquier-servidor-smtp/)

**Comment by ItzNotABug** [comment]
Hey @viriatusX,
I just checked it as I received it on email 🚀.

I'll add a step on `README.md` for this & keep this issue open anyway.
Thanks a ton.

**Comment by ItzNotABug** [comment]
Hey @psharma04, @viriatusX,
An official support for Docker x Ghosler is now possible out of the box.

Closing this!
