### ISSUE TITLE
SSL routines:ssl3_get_record

### ISSUE THREAD

**Issue by ghost** [ItzNotABug/ghosler#47]
`[2024-03-31 05:03:28 UTC] => [ERROR] => Newsletter: Error: D879469B597F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

How can i fix this?
I'm hosting on a home-server and using cloudflare tunnels for both ghost and ghosler.
Also i'm using sendgird as SMTP server

**Comment by ItzNotABug** [comment]
Does this help https://github.com/ItzNotABug/ghosler/issues/39#issuecomment-2021354525?

**Comment by ghost** [comment]
Oh, yeah!

I was using 587, changing for 465 worked just fine.
Thanks, mate. Ghosler it's a great project!
