### ISSUE TITLE
Add subtitles

### ISSUE THREAD

**Issue by viriatusX** [ItzNotABug/ghosler#58]
Hi! 
is it possible to update Ghosler with a checkbox to include the Subtitle?
https://forum.ghost.org/t/subtitles-in-newsletters-ghost-changelog/47949

Thanks

**Comment by ItzNotABug** [comment]
Hey @viriatusX,
Thanks for the feature suggestion.

This doesn't look too trivial to implement.
I'll bump my ghost version and take a look at how this is styled and implemented. Due to work, I cannot guarantee the ETAs on this though.

**Comment by ItzNotABug** [comment]
Completed via #59 🎉.
