### ISSUE TITLE
Login error Docker image

### ISSUE THREAD

**Issue by icu-nl** [ItzNotABug/ghosler#60]
After I run the docker-install.sh the image succesfully starts. And the login page is available http://mydomain.com:2369/login

However when I login with the credentials, it redirects (or submits?) to http://mydomain.com/login and seems the port number is missing.

---

Note: If you are UPDATING, use the same PORT & CONTAINER NAME!

Provide a port for Ghosler [Default: 2369] : 

Provide a name for Ghosler Container [Default: ghosler] : 

Starting Ghosler Docker installation..

**Comment by ItzNotABug** [comment]
Hey @icu-nl,
Did you update or was this a fresh install?

I have an idea of what might be causing this, just need to make sure.

**Comment by icu-nl** [comment]
Fresh install

**Comment by ItzNotABug** [comment]
> Fresh install

Thanks. I'll check.
In the meantime, you can edit the `docker-install.sh` & replace the `"${LATEST_VERSION}"` to a previous working version like `itznotabug/ghosler:0.97`.

---
Source - https://github.com/ItzNotABug/ghosler/blob/e8b87660923791f58e557ea7d93b1e0dd56f1468/docker-install.sh#L55

**Comment by icu-nl** [comment]
Using the 0.97 version I get the familiar login page, however the credentials as listed in the README do not work.
btw the 0.98 verision login page was looking different as well.

**Comment by ItzNotABug** [comment]
There shouldn't be any UI changes across these versions on the login page as you described.
Also, I just did a fresh install and the login works for me. When you login on a fresh install, does it navigate to dashboard?

**Comment by icu-nl** [comment]
Well this is what happens in my environment:

`curl -sSL https://raw.githubusercontent.com/ItzNotABug/ghosler/master/docker-install.sh -o docker-install.sh && chmod +x docker-install.sh && ./docker-install.sh

Note: If you are UPDATING, use the same PORT & CONTAINER NAME!

Provide a port for Ghosler [Default: 2369] : 

Provide a name for Ghosler Container [Default: ghosler] : 

Starting Ghosler Docker installation...

Unable to find image 'itznotabug/ghosler:0.98' locally
0.98: Pulling from itznotabug/ghosler
d25f557d7f31: Pull complete 
f61249306349: Pull complete 
22a81a0f8d1c: Pull complete 
bd06542006fd: Pull complete 
c4c112a38c18: Pull complete 
3391606c9aa9: Pull complete 
e98d64167a86: Pull complete 
cf9a7de9b4cc: Pull complete 
Digest: sha256:fb19bd8d00950a6a2998f35f28be36650398ee179fe828814b8243eaf08b5834
Status: Downloaded newer image for itznotabug/ghosler:0.98
8d8175f39d71373059327de25dc7498209f5f5e009c61306366489345b123b5b

Ghosler has been successfully installed and started.
`

And this is how the login page shows. Same problem.
<img width="1369" alt="image" src="https://github.com/ItzNotABug/ghosler/assets/118545386/bc802dab-f657-473b-bfa5-aafe1e5598f0">

**Comment by icu-nl** [comment]
Ok. I found en fixed the issue, fault on my side.
It seemed there were some residual ghosler docker volumes still present on my machine. After pruning the volumes everything works as it should.
