### ISSUE TITLE
Email not sent due to error (socket hang up)

### ISSUE THREAD

**Issue by Wobak** [ItzNotABug/ghosler#62]
Hello and thank you for your work on this.

I have an issue. I'm trying to setup everything with ghosler on containers, and while it worked while I was doing some tests, it suddenly stopped working. I'm not sure what I did wrong, I think I deleted a post while another was being published, and this seems to have broken stuff.

Now whenever I'm publishing a post, this is the error I get in the logs : 
```
ghosler  | Newsletter: Post received via webhook.
ghosler  | Newsletter: 2 users have enabled receiving newsletters.
ghosler  | Ghost: Site comments enabled: false
ghosler  | Newsletter: Error: socket hang up
ghosler  | TypeError: Cannot destructure property 'trackedLinks' of '(intermediate value)' as it is undefined.
ghosler  |     at Newsletter.send (file:///usr/src/app/utils/newsletter.js:33:16)
```

I tried deleting the container, putting it down & up, re-configuring everything, and yet I get this error.

Any idea on how to troubleshoot this?

Thanks !

**Comment by ItzNotABug** [comment]
Hey 👋,
could you tell what version of `ghosler` are you using?

**Comment by Wobak** [comment]
I pulled the latest from docker hub so 0.97

**Comment by Wobak** [comment]
I tried deleting the webhook and recreating, deleting the integration and webhook and going back from scratch, deleting the container and its config and re-spawning everything, error remains.

**Comment by ItzNotABug** [comment]
Hey 👋,
the latest should be `0.98` 🤔.

https://github.com/ItzNotABug/ghosler/releases/tag/0.98

**Comment by Wobak** [comment]
Sorry I was using the wrong image from Docker Hub. I upgraded to yours on 0.98, and still have the issue : 
```
ghosler  | Newsletter: Post received via webhook.
ghosler  | Newsletter: 2 users have enabled receiving newsletters.
ghosler  | Ghost: Site comments enabled: false
ghosler  | Newsletter: Error: socket hang up
ghosler  | TypeError: Cannot destructure property 'trackedLinks' of '(intermediate value)' as it is undefined.
ghosler  |     at Newsletter.send (file:///usr/src/app/utils/newsletter.js:38:17)
```

**Comment by ItzNotABug** [comment]
Hey again 👋,
I just tried a standard docker installation & was able to send an email.

Did you wipe the volumes too before installing a fresh version of `ghosler`?

---
I see only one particular area where the `trackedLinks` is not returned, which is in a `catch` block [here](https://github.com/ItzNotABug/ghosler/blob/e8b87660923791f58e557ea7d93b1e0dd56f1468/utils/newsletter.js#L167C11-L170C10).

This probably means one of the operation in the `try` block is failing, there are mainly 3 -
1. `ejs.renderFile` -  Renders the content for email
2. `injectUrlTracking` - Injects URL Tracking logic
3. `Widgets.replace` - Replaces bare-bones widgets with Ghost Cards

Could you provide some more info?
Like the Ghost CMS version and the content length of the Post? Is it too long?

**Comment by Wobak** [comment]
> Hey again 👋, I just tried a standard docker installation & was able to send an email.
> 
> Did you wipe the volumes too before installing a fresh version of `ghosler`?
> 
> I see only one particular area where the `trackedLinks` is not returned, which is in a `catch` block [here](https://github.com/ItzNotABug/ghosler/blob/e8b87660923791f58e557ea7d93b1e0dd56f1468/utils/newsletter.js#L167C11-L170C10).
> 
> This probably means one of the operation in the `try` block is failing, there are mainly 3 -
> 
> 1. `ejs.renderFile` -  Renders the content for email
> 2. `injectUrlTracking` - Injects URL Tracking logic
> 3. `Widgets.replace` - Replaces bare-bones widgets with Ghost Cards
> 
> Could you provide some more info? Like the Ghost CMS version and the content length of the Post? Is it too long?

Hey ! 

Sure can :) 
Ghost info : 
```
Version: [5.87.0](https://github.com/TryGhost/Ghost/releases/tag/v5.87.0)
Environment: production
Database: mysql8
Mail: SMTP
```

I just tried creating a post with 2 lines, it worked, so it is probably due to the content. The post I was trying to send contains mostly text, pictures and a gallery. Would you like me to link it to you privately, or should I try to see which of the parameters is causing this?

**Comment by Wobak** [comment]
OK I removed the gallery and it works. Should I avoid galleries or can you investigate on what's happening? :)

**Comment by ItzNotABug** [comment]
Hey 👋,
Thanks a ton for the updates.

I haven't used gallery yet so this never happened. Can you create a new issue as this seems to be resolved, sort of.

**Comment by Wobak** [comment]
Surely can.
