### ISSUE TITLE
Whitelist rather than Blacklist

### ISSUE THREAD

**Issue by psharma04** [ItzNotABug/ghosler#69]
Is it possible to have an inverted behaviour to the `#GhoslerIgnore` tag, where the default behaviour is not sending an email, but the tagged posts (something like `#GhoslerSend`) will be sent?

**Comment by ItzNotABug** [comment]
Hey 👋,
We could do that & I see its value too but that really wouldn't make much sense along with the `#GhoslerIgnore` tag honestly. 2 opposite tags don't really make sense atm, only one does and the ignore is already added.

Might probably think of something on this later but no ETAs.

**Comment by ItzNotABug** [comment]
Closing this as not planned atm as one of the tag is already available.
